// <auto-generated />
using System;
using AirportSim.Server.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AirportSim.Server.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SimulationDbContext))]
    [Migration("20260503141122_InitialFlightLog")]
    partial class InitialFlightLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AirportSim.Server.Domain.Entities.FlightLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AircraftType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("aircraft_type");

                    b.Property<string>("AssignedGate")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("assigned_gate");

                    b.Property<int>("DelayMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("delay_minutes");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("destination");

                    b.Property<double>("FinalFuelPct")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision")
                        .HasColumnName("final_fuel_pct");

                    b.Property<string>("FlightId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("flight_id");

                    b.Property<string>("FlightType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("flight_type");

                    b.Property<int>("GoAroundCount")
                        .HasColumnType("integer")
                        .HasColumnName("go_around_count");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("origin");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("outcome");

                    b.Property<DateTime>("SimulatedTime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("simulated_time");

                    b.Property<DateTime>("WallClockTime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("wall_clock_time");

                    b.HasKey("Id");

                    b.HasIndex("FlightId")
                        .HasDatabaseName("ix_flight_log_flight_id");

                    b.HasIndex("Outcome")
                        .HasDatabaseName("ix_flight_log_outcome");

                    b.HasIndex("SimulatedTime")
                        .HasDatabaseName("ix_flight_log_simulated_time");

                    b.ToTable("flight_log", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
